### ISSUE TITLE
I use content_blocks 0.5 - Composer allowed only 0.4

### ISSUE THREAD

**Issue by CMS-Internetsolutions** [t3solution/t3s_swiper#2]
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Root composer.json requires t3s/t3s-swiper * -> satisfiable by t3s/t3s-swiper[dev-main, v0.0.1, 0.0.1.x-dev, v0.0.2, 0.0.2.x-dev, 9999999-dev].
    - t3s/t3s-swiper[dev-main, v0.0.1, ..., 0.0.2.x-dev] require contentblocks/content-blocks ^0.4 -> found contentblocks/content-blocks[0.4.0] but it conflicts with your root composer.json require (^0.5).

What is the best practice downgrade to 0.4?

Best Regard's very cool Extension!!

## Requirements
- TYPO3 >= 12.4
- ext:content_blocks >= 0.4.0

**Comment by t3solution** [comment]
There is a bugfix release v0.0.3 on Packagist!

**Comment by CMS-Internetsolutions** [comment]
Thank you!
